language: node_js
node_js:
  - '10.14.1'
cache: npm
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
  - npm run createdb

script:
  - npm test
after_success:
  - npm run coverage
