language: node_js
node_js:
  - "stable"
before_script: 
  - npm install 
script: 
  - npm test
after_success: 
  - npm run coverage

env:
  global:
    - CC_TEST_REPORTER_ID=5b871f77cba7f281ded56f81fdd33ea83c0769a1173b81789da3c2e079f1af2a
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
addons:
  chrome: stable

before_install:
  - nvm install                         
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle} 
  - npm install                         

before_script: bundle exec rake db:create db:migrate
script:
  - bundle exec rubocop -DESP           
  - bundle exec rake                   
 
  - npm test                            
after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json