language: node_js
node_js:
  - 'stable'
services:
  - postgresql
cache:
  directories:
    - $HOME/.npm
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
  - npm run createdb

script:
  - npm test
after_success:
  - npm run coverage
