import status from './status';

const orders = [
  {
    id: 1,
    from: '25 Lekki Lagos',
    placedBy: 11,
    weight: 3.5,
    weightMetric: 'Kg',
    sentOn: new Date().toLocaleString(),
    deliveredOn: new Date().toLocaleString(),
    to: '39 Alausa Ikeja Lagos',
    status: status.TRANSITING,
    currentLocation: '25 Lekki Lagos',
  },
  {
    id: 2,
    placedBy: 12,
    weight: 5.6,
    weightMetric: 'Kg',
    sentOn: new Date().toLocaleString(),
    deliveredOn: new Date().toLocaleString(),
    from: '24 Ogbomosho road, Ibadan',
    to: '10 Obaro way, Ilupeju Lagos',
    status: status.DELIVERED,
    currentLocation: new Date().toLocaleString(),
  },
  {
    id: 3,
    placedBy: 13,
    weight: 0.45,
    weightMetric: 'Kg',
    sentOn: new Date().toLocaleString(),
    deliveredOn: new Date().toLocaleString(),
    from: '45 Abraham Adesanya Estate Ajah Lagos',
    to: '22 Olorundare close, Iyana Apaja, Lagos',
    status: status.DELIVERED,
    currentLocation: new Date().toLocaleString(),
  },
  {
    id: 4,
    placedBy: 11,
    weight: 0.9,
    weightMetric: 'Kg',
    sentOn: new Date().toLocaleString(),
    deliveredOn: new Date().toLocaleString(),
    from: '22 Joseph Street Idumota Lagos',
    to: '44 Akinola estate, Olokonla Lagos',
    status: status.TRANSITING,
    currentLocation: new Date().toLocaleString(),
  },
  {
    id: 5,
    placedBy: 15,
    weight: 0.19,
    weightMetric: 'Kg',
    sentOn: new Date().toLocaleString(),
    deliveredOn: new Date().toLocaleString(),
    from: '104A Doherty lane, Lekki, Lagos',
    to: 'B324A Banana Island Ikoyi, Lagos',
    status: status.PLACED,
    currentLocation: new Date().toLocaleString(),
  },
];

export default orders;
